# Generated by Django 6.0.6 on 2026-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('bacs', 'BACS transfer'), ('cash', 'Cash')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period',
            field=models.CharField(help_text='e.g. January 2026 or Autumn Term 2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
