# Generated by Django 6.0.6 on 2026-06-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_reminder_sent_at'),
        ('members', '0008_member_medical_info_memberapplication_medical_info'),
        ('organisations', '0005_organisation_custom_css_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Termly'), ('annual', 'Annual'), ('custom', 'Custom / Manual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_policies', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Billing policy',
                'verbose_name_plural': 'Billing policies',
                'ordering': ['organisation', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingpolicy'),
        ),
        migrations.CreateModel(
            name='OrgTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Autumn Term 2025', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Term',
                'ordering': ['organisation', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed amount (£)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auto_apply', models.BooleanField(default=False, help_text='Automatically apply to all new members on this policy')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.billingpolicy')),
            ],
            options={
                'verbose_name': 'Policy discount',
                'ordering': ['policy', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='members.member')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_discounts', to='billing.policydiscount')),
            ],
            options={
                'verbose_name': 'Member discount',
                'unique_together': {('member', 'discount')},
            },
        ),
    ]
