# Generated by Django 6.1 on 2026-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billingpolicy_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stripe invoice this row mirrors, for subscription payments. Used to make webhook redelivery a no-op.', max_length=255),
        ),
    ]
