# Generated by Django 6.0.6 on 2026-06-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
