# Generated by Django 6.0.6 on 2026-06-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_discount_amount_billingpolicy_and_more'),
        ('classes', '0003_class_max_capacity_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='billing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='billing.billingpolicy'),
        ),
    ]
