# Generated by Django 6.0.6 on 2026-08-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_address_line1_member_address_line2'),
        ('organisations', '0005_organisation_custom_css_organisation_logo'),
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional — lets you tell apart multiple sessions run on the same date (e.g. "Primary", "Morning").', max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='progression.assessment')),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attendance', to='members.member')),
                ('new_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='progression.progressionstage')),
                ('progression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='progression.memberprogression')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='progression.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'member')},
            },
        ),
    ]
