# Generated by Django 6.0.6 on 2026-06-21 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_phone_organisation_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmember',
            name='coaching_licence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='coaching_licence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='dbs_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='dbs_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('recipient_label', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organisations.organisation')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
