# Generated by Django 6.0.6 on 2026-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='licence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='licence_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
