# Generated by Django 6.0.6 on 2026-06-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_discount_amount_billingpolicy_and_more'),
        ('members', '0008_member_medical_info_memberapplication_medical_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='billing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='billing.billingpolicy'),
        ),
        migrations.AddField(
            model_name='member',
            name='retention_notes',
            field=models.TextField(blank=True, help_text='Reason for retaining data beyond the standard period'),
        ),
    ]
