# Generated by Django 6.0.6 on 2026-07-17 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_archived_at_member_billing_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the current portal token was issued — used to auto-rotate stale links'),
        ),
    ]
