# Generated by Django 6.0.6 on 2026-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_archived_at_member_billing_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='decided_at',
            field=models.DateTimeField(blank=True, help_text='When the application was approved or rejected', null=True),
        ),
    ]
