# Generated by Django 6.0.6 on 2026-07-17 20:35

from django.db import migrations, models


def backfill_decided_at(apps, schema_editor):
    MemberApplication = apps.get_model('members', 'MemberApplication')
    MemberApplication.objects.filter(
        decided_at__isnull=True,
    ).exclude(status='pending').update(decided_at=models.F('submitted_at'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_anonymised_at_memberapplication_decided_at'),
    ]

    operations = [
        migrations.RunPython(backfill_decided_at, noop),
    ]
