# Generated by Django 6.0.6 on 2026-07-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_token_created_at'),
        ('members', '0011_backfill_application_decided_at'),
    ]

    operations = [
    ]
