# Generated by Django 6.0.6 on 2026-06-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_merge_20260717_2313'),
        ('organisations', '0005_organisation_custom_css_organisation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Smith Family', max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='% discount applied to every member in this group', max_digits=5)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Family group',
                'ordering': ['organisation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.familygroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='members.member')),
            ],
            options={
                'unique_together': {('family_group', 'member')},
            },
        ),
        migrations.AddField(
            model_name='familygroup',
            name='members',
            field=models.ManyToManyField(related_name='family_groups', through='members.FamilyGroupMember', to='members.member'),
        ),
    ]
